// Computes WCAG 2.x contrast ratios for token pairs parsed from src/tokens.css
import { readFileSync, writeFileSync } from 'node:fs';
const css = readFileSync(new URL('../src/tokens.css', import.meta.url), 'utf8');
const vars = Object.fromEntries([...css.matchAll(/--(c-[a-z-]+):\s*(#[0-9a-f]{6})/gi)].map(m => [m[1], m[2]]));
const lum = (hex) => { const c = [1,3,5].map(i => parseInt(hex.slice(i,i+2),16)/255).map(v => v <= 0.03928 ? v/12.92 : ((v+0.055)/1.055)**2.4); return 0.2126*c[0]+0.7152*c[1]+0.0722*c[2]; };
const ratio = (a,b) => { const [x,y] = [lum(a),lum(b)].sort((p,q)=>q-p); return (x+0.05)/(y+0.05); };
// [foreground, background, kind, usage]
const pairs = [
  ['c-ink','c-paper','text','Body text on page'],
  ['c-ink','c-surface','text','Body text on cards/inputs'],
  ['c-ink','c-sand','text','Text on sand panels / table header'],
  ['c-ink-muted','c-paper','text','Hint / secondary text on page'],
  ['c-ink-muted','c-surface','text','Hint text on inputs/cards'],
  ['c-ink-muted','c-sand','text','Secondary text on sand'],
  ['c-on-primary','c-primary','text','Primary button text'],
  ['c-on-primary','c-primary-hover','text','Primary button hover text'],
  ['c-secondary-text','c-surface','text','Secondary button text'],
  ['c-secondary-text','c-paper','text','Secondary button text on page'],
  ['c-on-danger','c-danger','text','Danger button text'],
  ['c-on-danger','c-danger-hover','text','Danger button hover text'],
  ['c-danger','c-surface','text','Error message text on white'],
  ['c-danger','c-paper','text','Error message text on page'],
  ['c-success-text','c-success-bg','text','Success toast text'],
  ['c-info-text','c-info-bg','text','Info toast text'],
  ['c-error-text','c-error-bg','text','Error toast text'],
  ['c-disabled-text','c-disabled-bg','text','Disabled control text (exempt, shown for info)'],
  ['c-primary','c-paper','text','Links / sort headers in primary on page'],
  ['c-border','c-paper','ui','Input/checkbox border on page'],
  ['c-border','c-surface','ui','Input/checkbox border on white'],
  ['c-border','c-sand','ui','Border on sand'],
  ['c-focus','c-paper','ui','Focus ring on page'],
  ['c-focus','c-surface','ui','Focus ring on white'],
  ['c-focus','c-sand','ui','Focus ring on sand'],
  ['c-on-deep','c-deep','text','Header and hero heading text'],
  ['c-on-deep-muted','c-deep','text','Hero intro text'],
  ['c-accent','c-deep','ui','Amber tick-mark strip (decorative) on deep green'],
  ['c-on-deep','c-deep','ui','Focus ring on dark header'],
  ['c-primary','c-paper','ui','Selected tab indicator / button boundary'],
  ['c-danger','c-surface','ui','Invalid input border'],
];
const rows = []; let fails = 0;
for (const [f,b,kind,use] of pairs) {
  const r = ratio(vars[f], vars[b]); const need = kind === 'text' ? 4.5 : 3;
  const exempt = use.includes('exempt');
  const pass = r >= need; if (!pass && !exempt) fails++;
  rows.push(`| ${use} | \`${f}\` ${vars[f]} | \`${b}\` ${vars[b]} | ${kind} | ${r.toFixed(2)}:1 | ${need}:1 | ${pass ? 'Pass' : exempt ? 'Below (exempt)' : '**FAIL**'} |`);
}
const md = `# Contrast report\n\nGenerated by \`scripts/contrast-check.mjs\` on ${new Date().toISOString().slice(0,10)} from \`src/tokens.css\`.\n\nThresholds: 4.5:1 text, 3:1 for UI boundaries/focus indicators (WCAG 1.4.3, 1.4.11, 2.4.13).\n\n| Usage | Foreground | Background | Type | Ratio | Required | Result |\n|---|---|---|---|---|---|---|\n${rows.join('\n')}\n\n**${pairs.length} pairs checked, ${fails} failing.**\n`;
writeFileSync(new URL('../docs/contrast-report.md', import.meta.url), md);
console.log(`${pairs.length} pairs, ${fails} failing`); process.exit(fails ? 1 : 0);
